### ISSUE TITLE
benchmarks for go not working when using remote runner

### ISSUE THREAD

**Issue by litzenberger** [ipfs/benchmarks#110]
```
INFO [1546178378903] (31093 on ip-172-31-44-15): running  [cat /tmp/out/unixFsAddGo.json] on [147.75.33.155]
(node:31093) UnhandledPromiseRejectionWarning: Error: (node:29024) UnhandledPromiseRejectionWarning: Error: spawn ipfs ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:29024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29024) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

    at remoteExec (/data/ipfs-benchmarks/runner/remote.js:22:18)
    at f (/data/ipfs-benchmarks/runner/node_modules/once/once.js:25:25)
    at Duplexify.<anonymous> (/data/ipfs-benchmarks/runner/node_modules/ssh-exec-plus/index.js:155:5)
    at Duplexify.emit (events.js:187:15)
    at endReadableNT (/data/ipfs-benchmarks/runner/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:31093) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31093) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is IPFS installed on the benchmark server?

**Comment by Elexy** [comment]
https://github.com/ipfs/benchmarks/pull/115
