### ISSUE TITLE
Unable to store some tests in DB

### ISSUE THREAD

**Issue by litzenberger** [ipfs/benchmarks#117]
```INFO [1546281070267] (21402 on ip-172-31-44-15): point:  {"name":"addMultiKb","warmup":"off","description":"Add 101 1 KB files to local","file_set":"Hundred1KBFile","date":"2018-12-31T18:31:00.286Z","file":"Hundred1KBFile","meta":{"version":{"version":"0.34.0-rc.0","repo":7,"commit":""},"project":"js-ipfs","commit":"7bcc49615e54f09c34bae07c994e3be3d870fe1f","branch":"master","guid":"33c04690-0d29-11e9-95c6-a387bf343229"},"duration":{"s":4,"ms":535.500524},"cpu":[{"model":"Intel(R) Atom(TM) CPU  C2550  @ 2.40GHz","speed":2600,"times":{"user":122128100,"nice":696600,"sys":21311100,"idle":34270511500,"irq":0}},{"model":"Intel(R) Atom(TM) CPU  C2550  @ 2.40GHz","speed":2600,"times":{"user":127373200,"nice":534300,"sys":21324200,"idle":34290173500,"irq":0}},{"model":"Intel(R) Atom(TM) CPU  C2550  @ 2.40GHz","speed":2600,"times":{"user":113756000,"nice":670000,"sys":14009900,"idle":34322798400,"irq":0}},{"model":"Intel(R) Atom(TM) CPU  C2550  @ 2.40GHz","speed":2600,"times":{"user":115006000,"nice":930900,"sys":13437500,"idle":34322589200,"irq":0}}],"loadAvg":[1.2138671875,0.9765625,0.4833984375],"memory":4813271040}
(node:21402) UnhandledPromiseRejectionWarning: Error: A 400 Bad Request error occurred: {"error":"unable to parse 'multiPeerTransfer,warmup=off,commit=7bcc49615e54f09c34bae07c994e3be3d870fe1f,project=js-ipfs,file_set=OneKBFile,version=0.34.0-rc.0,repo=7,guid=33c04690-0d29-11e9-95c6-a387bf343229,sha=tbd,branch=master duration=468.717883,ipfs_sha=undefined 1546281070266000000': invalid boolean\nunable toparse 'multiPeerTransfer,warmup=off,commit=7bcc49615e54f09c34bae07c994e3be3d870fe1f,project=js-ipfs,file_set=OneMBFile,version=0.34.0-rc.0,repo=7,guid=33c04690-0d29-11e9-95c6-a387bf343229,sha=tbd,branch=master duration=974.796503,ipfs_sha=undefined 1546281070266000000': invalid boolean\nunable to parse 'multiPeerTransfer,warmup=off,commit=7bcc49615e54f09c34bae07c994e3be3d870fe1f,project=js-ipfs,file_set=One4MBFile,version=0.34.0-rc.0,repo=7,guid=33c04690-0d29-11e9-95c6-a387bf343229,sha=tbd,branch=master duration=1434.165117,ipfs_sha=undefined 1546281070266000000': invalid boolean\nunable to parse 'multiPeerTransfer,warmup=off,commit=7bcc49615e54f09c34bae07c994e3be3d870fe1f,project=js-ipfs,file_set=One64MBFile,version=0.34.0-rc.0,repo=7,guid=33c04690-0d29-11e9-95c6-a387bf343229,sha=tbd,branch=master duration=8021.973649,ipfs_sha=undefined 1546281070266000000': invalid boolean"}

    at new RequestError (/data/ipfs-benchmarks/runner/node_modules/influx/lib/src/pool.js:52:28)
    at IncomingMessage.<anonymous> (/data/ipfs-benchmarks/runner/node_modules/influx/lib/src/pool.js:62:53)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:21402) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:21402) UnhandledPromiseRejectionWarning: Error: A 400 Bad Request error occurred: {"error":"unable to parse 'addMultiKb,warmup=off,commit=7bcc49615e54f09c34bae07c994e3be3d870fe1f,project=js-ipfs,file_set=Hundred1KBFile,version=0.34.0-rc.0,repo=7,guid=33c04690-0d29-11e9-95c6-a387bf343229,sha=tbd,branch=master duration=4535.500524,ipfs_sha=undefined 1546281070267000000': invalid boolean"}

    at new RequestError (/data/ipfs-benchmarks/runner/node_modules/influx/lib/src/pool.js:52:28)
    at IncomingMessage.<anonymous> (/data/ipfs-benchmarks/runner/node_modules/influx/lib/src/pool.js:62:53)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:21402) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Comment by litzenberger** [comment]
This has been fixed.  If it doesn't upload the results, the link in Grafana will show 'no upload'
<img width="1703" alt="screen shot 2019-01-01 at 11 18 16 am" src="https://user-images.githubusercontent.com/6003995/50574885-f9f06100-0db6-11e9-91ed-d910f379c369.png">
