### ISSUE TITLE
Browser tests in production fail due to timeout

### ISSUE THREAD

**Issue by litzenberger** [ipfs/benchmarks#174]
Browser tests fail for tests that use the public Rendezvous server.
I can ping it but the tests fail.

```
ubuntu@js-ipfs-benchmarking:~$ ping 95.179.134.100
PING 95.179.134.100 (95.179.134.100) 56(84) bytes of data.
64 bytes from 95.179.134.100: icmp_seq=1 ttl=58 time=0.845 ms
64 bytes from 95.179.134.100: icmp_seq=2 ttl=58 time=0.940 ms
64 bytes from 95.179.134.100: icmp_seq=3 ttl=58 time=0.861 ms
```
Curl works also
```
curl http://95.179.134.100:9090/

```
to test:

`ubuntu@js-ipfs-benchmarking:~/ipfs/tests$ node peer-transfer.browser.js`

Is there anything on the server preventing from listening?
```
Swarm listening on /dnsaddr/95.179.134.100/tcp/9090/ws/p2p-websocket-star/ipfs/QmaqBSvh8NKmG59yg3SXceGpdvRE5AXixmkAN2TRPcxfMF
main.chunk.js:2487 
Swarm listening on /dnsaddr/95.179.134.100/tcp/9090/ws/p2p-websocket-star/ipfs/QmTbcHDrFDu3Mebptnsa4pUsexhhgRM3TnqujEhqwXgqJF
```

**Comment by litzenberger** [comment]
I added more logging on the node side.  Doesn't  appear to connect to the Rendezvous server.  Here is the expected put from running `node peer-transfer.browser.js`:

```
rons-MBP:tests ronlitzenberger$ node peer-transfer.browser.js
Verifying File onekbfile
Verifying Directory hundred1kbfile
Verifying File one62kbfile
Verifying File one64kbfile
Verifying File one512kbfile
Verifying File one768kbfile
Verifying File one1023kbfile
Verifying File onembfile
Verifying File one4mbfile
Verifying File one8mbfile
Verifying File one64mbfile
Verifying File one128mbfile
Verifying File one512mbfile
Verifying File onegbfile
Files Verified
PAGE LOG: Swarm listening on /dnsaddr/95.179.134.100/tcp/9090/ws/p2p-websocket-star/ipfs/QmXRAG5wFEFp78qFx6utuNLv3naSPfxcUUSTDbCb7ymfsX
PAGE LOG: Swarm listening on /dnsaddr/95.179.134.100/tcp/9090/ws/p2p-websocket-star/ipfs/QmfBuHHNRFtQXjw41K7J2zH3kReVoDzaM4h9zGqXGnTSrB
Writing output in a multiple files
┌────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────┬─────────────────┐
│ Test               │ Warmup             │ Description                                      │ File Set           │ Duration        │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼─────────────────┤
│ peerTransferBrows… │ off                │ Transfer file between peers in the browser       │ OneKBFile          │ s:3 ms: 170.455 │
```

**Comment by litzenberger** [comment]
It uses websockets for the connection.

`ws://95.179.134.100:9090/socket.io/?EIO=3&transport=websocket'`

**Comment by Elexy** [comment]
@eefahy could there be anything in the way of hitting the rendezvous server from the bare metal machine?

**Comment by Elexy** [comment]
The problem seems to be some missing piece.

I did this: https://github.com/libp2p/js-libp2p-websocket-star-rendezvous#usage
changed the endpoint:
```javascript
const node = new IPFS({ repo: String(uuidv1()),
      config: {
        Addresses: {
          Swarm: [
            '/dnsaddr/127.0.0.1/tcp/9090/ws/p2p-websocket-star/'
          ]
        }
      }
    })
    const node2 = new IPFS({ repo: String(uuidv1()),
      config: {
        Addresses: {
          Swarm: [
            '/dnsaddr/127.0.0.1/tcp/9090/ws/p2p-websocket-star/'
          ]
        }
      }
    })
```
and then ran:
```bash
elexy@operations:~/ipfs/tests$ npm run build-browser

> ipfs-benchmarks@0.1.0 build-browser /home/elexy/ipfs/tests
> ./util/build-browser-test.sh

/home/elexy/ipfs/tests/browser
up to date in 38.534s

> browser@0.1.0 build /home/elexy/ipfs/tests/browser
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  928.59 KB        build/static/js/1.22171c9b.chunk.js
  26.69 KB (-7 B)  build/static/js/main.443db77f.chunk.js
  16.05 KB         build/static/css/1.258f6d5f.chunk.css
  763 B            build/static/js/runtime~main.4a686d48.js
  511 B            build/static/css/main.e33b6fb5.chunk.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  http://bit.ly/CRA-deploy

elexy@operations:~/ipfs/tests$ node peer-transfer.browser.js
Verifying File onekbfile
Verifying Directory hundred1kbfile
Verifying File one62kbfile
Verifying File one64kbfile
Verifying File one512kbfile
Verifying File one768kbfile
Verifying File one1023kbfile
Verifying File onembfile
Verifying File one4mbfile
Verifying File one8mbfile
Verifying File one64mbfile
Verifying File one128mbfile
Verifying File one512mbfile
Verifying File onegbfile
Files Verified
{ TimeoutError: waiting for selector ".peerTransfer_s_ready" failed: timeout 30000ms exceeded
    at new WaitTask (/home/elexy/ipfs/tests/node_modules/puppeteer/lib/FrameManager.js:991:28)
    at Frame._waitForSelectorOrXPath (/home/elexy/ipfs/tests/node_modules/puppeteer/lib/FrameManager.js:882:12)
    at Frame.waitForSelector (/home/elexy/ipfs/tests/node_modules/puppeteer/lib/FrameManager.js:836:17)
    at Frame.waitFor (/home/elexy/ipfs/tests/node_modules/puppeteer/lib/FrameManager.js:821:19)
    at Page.waitFor (/home/elexy/ipfs/tests/node_modules/puppeteer/lib/Page.js:1022:29)
    at peerTransferBrowser (/home/elexy/ipfs/tests/peer-transfer.browser.js:14:24)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }
waiting for selector ".peerTransfer_s_ready" failed: timeout 30000ms exceeded
```

**Comment by litzenberger** [comment]
Added more browser logging showed an error due to wrong version of libp2p:
```
Error: Error: There is already a transport with this key
```

Working on updating libp2p to .0.24.2
