### ISSUE TITLE
Broken on Node 11

### ISSUE THREAD

**Issue by mcollina** [ipfs/benchmarks#41]
```js
$ nvm use 11
node Now using node v11.3.0 (npm v6.4.1)
$ node local-add.js
(node:94288) UnhandledPromiseRejectionWarning: Error: Callback was already called.
    at /Users/matteo/Repositories/ipfs-benchmarks/tests/node_modules/async/internal/onlyOnce.js:9:32
    at _locker.lock (/Users/matteo/Repositories/ipfs-benchmarks/tests/node_modules/ipfs-repo/src/index.js:170:16)
    at lock.then.catch.err (/Users/matteo/Repositories/ipfs-benchmarks/tests/node_modules/ipfs-repo/src/lock.js:40:19)
(node:94288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:94288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Maybe it's not us, we might need to escalate.

**Comment by litzenberger** [comment]
@mcollina Did you rebuild after changing versions?  I do that when going between different versions of node to get past this error.

**Comment by litzenberger** [comment]
To scwith node version, rm node_modules then npm install.  

```js
rons-MacBook-Pro:tests ronlitzenberger$ nvm current
v11.3.0
rons-MacBook-Pro:tests ronlitzenberger$ node local-add
Swarm listening on /ip4/127.0.0.1/tcp/4022/ws/ipfs/QmSxYJBid9EUdV61T9dUELAsc2FncyQWaSEvm4ztcURiur
Swarm listening on /ip4/127.0.0.1/tcp/4012/ipfs/QmSxYJBid9EUdV61T9dUELAsc2FncyQWaSEvm4ztcURiur
Swarm listening on /ip4/192.168.1.66/tcp/4012/ipfs/QmSxYJBid9EUdV61T9dUELAsc2FncyQWaSEvm4ztcURiur
Swarm listening on /ip4/127.0.0.1/tcp/4023/ws/ipfs/QmNc18FMrKks42Nd2PVwtBHdSvmfkhcvANDBe9byVuXd3f
Swarm listening on /ip4/127.0.0.1/tcp/4013/ipfs/QmNc18FMrKks42Nd2PVwtBHdSvmfkhcvANDBe9byVuXd3f
Swarm listening on /ip4/192.168.1.66/tcp/4013/ipfs/QmNc18FMrKks42Nd2PVwtBHdSvmfkhcvANDBe9byVuXd3f
Swarm listening on /ip4/127.0.0.1/tcp/4024/ws/ipfs/QmbZRmAfarFJYDUwa5WSQ1FazCQ72iA7Hp3qE2ZPhRF7is
Swarm listening on /ip4/127.0.0.1/tcp/4014/ipfs/QmbZRmAfarFJYDUwa5WSQ1FazCQ72iA7Hp3qE2ZPhRF7is
Swarm listening on /ip4/192.168.1.66/tcp/4014/ipfs/QmbZRmAfarFJYDUwa5WSQ1FazCQ72iA7Hp3qE2ZPhRF7is
Swarm listening on /ip4/127.0.0.1/tcp/4025/ws/ipfs/QmeKizHABFpHtEZoJiuZJmvVtC1yXi2MrRZ3UqgnqrUqet
Swarm listening on /ip4/127.0.0.1/tcp/4015/ipfs/QmeKizHABFpHtEZoJiuZJmvVtC1yXi2MrRZ3UqgnqrUqet
Swarm listening on /ip4/192.168.1.66/tcp/4015/ipfs/QmeKizHABFpHtEZoJiuZJmvVtC1yXi2MrRZ3UqgnqrUqet
Swarm listening on 
/ip4/127.0.0.1/tcp/4026/ws/ipfs/QmdX7uA1nQq1oghmxHhpKfb7VbvjETPd6DihW4w5Ht52Tt
Swarm listening on /ip4/127.0.0.1/tcp/4016/ipfs/QmdX7uA1nQq1oghmxHhpKfb7VbvjETPd6DihW4w5Ht52Tt
Swarm listening on /ip4/192.168.1.66/tcp/4016/ipfs/QmdX7uA1nQq1oghmxHhpKfb7VbvjETPd6DihW4w5Ht52Tt
{ size: 1024, name: 'OneKBFile' }
{ size: 1048576, name: 'OneMBFile' }
{ size: 4194304, name: 'One4MBFile' }
{ size: 67108864, name: 'One64MBFile' }
{ size: 1024, name: 'OneKBFile' }
{ size: 1048576, name: 'OneMBFile' }
{ size: 4194304, name: 'One4MBFile' }
{ size: 67108864, name: 'One64MBFile' }
Writing output in a multiple files
┌────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────┬────────────────────┐
│ Test               │ Sub Test           │ Description                                      │ File Set           │ Duration           │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ unixFsAdd          │ empty-repo         │ Add file to local repo using unixFS engine       │ OneKBFile          │ s:0 ms: 50.205168  │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ unixFsAdd          │ empty-repo         │ Add file to local repo using unixFS engine       │ OneMBFile          │ s:0 ms: 100.91727  │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ unixFsAdd          │ empty-repo         │ Add file to local repo using unixFS engine       │ One4MBFile         │ s:0 ms: 212.282427 │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ unixFsAdd          │ empty-repo         │ Add file to local repo using unixFS engine       │ One64MBFile        │ s:3 ms: 133.491623 │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ unixFsAdd          │ populated-repo     │ Add file to local repo using unixFS engine       │ OneKBFile          │ s:0 ms: 10.782894  │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ unixFsAdd          │ populated-repo     │ Add file to local repo using unixFS engine       │ OneMBFile          │ s:0 ms: 12.62467   │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ unixFsAdd          │ populated-repo     │ Add file to local repo using unixFS engine       │ One4MBFile         │ s:0 ms: 42.693402  │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ unixFsAdd          │ populated-repo     │ Add file to local repo using unixFS engine       │ One64MBFile        │ s:0 ms: 680.588206 │
└────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────┴────────────────────┘
Removed ./data/ipfs
```
