### ISSUE TITLE
libp2p node is not started yet

### ISSUE THREAD

**Issue by mcollina** [ipfs/benchmarks#63]
```
$ STAGE=remote node multi-peer-transfer.js
Verifying File OneKBFile
Verifying Directory Hundred1KBFile
Verifying File One62KBFile
Verifying File One64KBFile
Verifying File One512KBFile
Verifying File One768KBFile
Verifying File One1023MBFile
Verifying File OneMBFile
Verifying File One4MBFile
Verifying File One8MBFile
Verifying File One64MBFile
Verifying File One128MBFile
Verifying File One512MBFile
Verifying File OneGBFile
Files Verified
Swarm listening on /ip4/127.0.0.1/tcp/4012/ipfs/QmSxYJBid9EUdV61T9dUELAsc2FncyQWaSEvm4ztcURiur
Swarm listening on /ip4/192.168.1.222/tcp/4012/ipfs/QmSxYJBid9EUdV61T9dUELAsc2FncyQWaSEvm4ztcURiur
Swarm listening on /ip4/127.0.0.1/tcp/4022/ws/ipfs/QmSxYJBid9EUdV61T9dUELAsc2FncyQWaSEvm4ztcURiur
Swarm listening on /ip4/127.0.0.1/tcp/4013/ipfs/QmNc18FMrKks42Nd2PVwtBHdSvmfkhcvANDBe9byVuXd3f
Swarm listening on /ip4/192.168.1.222/tcp/4013/ipfs/QmNc18FMrKks42Nd2PVwtBHdSvmfkhcvANDBe9byVuXd3f
Swarm listening on /ip4/127.0.0.1/tcp/4023/ws/ipfs/QmNc18FMrKks42Nd2PVwtBHdSvmfkhcvANDBe9byVuXd3f
Swarm listening on /ip4/127.0.0.1/tcp/4014/ipfs/QmbZRmAfarFJYDUwa5WSQ1FazCQ72iA7Hp3qE2ZPhRF7is
Swarm listening on /ip4/192.168.1.222/tcp/4014/ipfs/QmbZRmAfarFJYDUwa5WSQ1FazCQ72iA7Hp3qE2ZPhRF7is
Swarm listening on /ip4/127.0.0.1/tcp/4024/ws/ipfs/QmbZRmAfarFJYDUwa5WSQ1FazCQ72iA7Hp3qE2ZPhRF7is
Swarm listening on /ip4/127.0.0.1/tcp/4015/ipfs/QmeKizHABFpHtEZoJiuZJmvVtC1yXi2MrRZ3UqgnqrUqet
Swarm listening on /ip4/192.168.1.222/tcp/4015/ipfs/QmeKizHABFpHtEZoJiuZJmvVtC1yXi2MrRZ3UqgnqrUqet
Swarm listening on /ip4/127.0.0.1/tcp/4025/ws/ipfs/QmeKizHABFpHtEZoJiuZJmvVtC1yXi2MrRZ3UqgnqrUqet
Swarm listening on /ip4/127.0.0.1/tcp/4016/ipfs/QmdX7uA1nQq1oghmxHhpKfb7VbvjETPd6DihW4w5Ht52Tt
Swarm listening on /ip4/192.168.1.222/tcp/4016/ipfs/QmdX7uA1nQq1oghmxHhpKfb7VbvjETPd6DihW4w5Ht52Tt
Swarm listening on /ip4/127.0.0.1/tcp/4026/ws/ipfs/QmdX7uA1nQq1oghmxHhpKfb7VbvjETPd6DihW4w5Ht52Tt
Writing output in a multiple files
┌────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────┬────────────────────┐
│ Test               │ Sub Test           │ Description                                      │ File Set           │ Duration           │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ multiPeerTransfer  │ empty-repo         │ Description of benchamrk                         │ OneKBFile          │ s:0 ms: 364.174486 │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ multiPeerTransfer  │ empty-repo         │ Description of benchamrk                         │ OneMBFile          │ s:0 ms: 734.050394 │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ multiPeerTransfer  │ empty-repo         │ Description of benchamrk                         │ One4MBFile         │ s:0 ms: 945.971094 │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ multiPeerTransfer  │ empty-repo         │ Description of benchamrk                         │ One64MBFile        │ s:6 ms: 503.684288 │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ multiPeerTransfer  │ populated-repo     │ Description of benchamrk                         │ OneKBFile          │ s:0 ms: 1.532656   │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ multiPeerTransfer  │ populated-repo     │ Description of benchamrk                         │ OneMBFile          │ s:0 ms: 4.923811   │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ multiPeerTransfer  │ populated-repo     │ Description of benchamrk                         │ One4MBFile         │ s:0 ms: 8.442353   │
├────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
│ multiPeerTransfer  │ populated-repo     │ Description of benchamrk                         │ One64MBFile        │ s:0 ms: 273.107513 │
└────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────┴────────────────────┘
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: The libp2p node is not started yet
    at Node.dialProtocol (/Users/matteo/Repositories/js-ipfs/node_modules/libp2p/src/index.js:236:5)
    at Network._dialPeer (/Users/matteo/Repositories/js-ipfs/node_modules/ipfs-bitswap/src/network.js:165:17)
    at Network.sendMessage (/Users/matteo/Repositories/js-ipfs/node_modules/ipfs-bitswap/src/network.js:129:10)
    at DecisionEngine._sendSafeBlocks (/Users/matteo/Repositories/js-ipfs/node_modules/ipfs-bitswap/src/decision-engine/index.js:83:18)
    at eachSeries (/Users/matteo/Repositories/js-ipfs/node_modules/ipfs-bitswap/src/decision-engine/index.js:65:14)
    at /Users/matteo/Repositories/js-ipfs/node_modules/async/internal/withoutIndex.js:9:16
    at replenish (/Users/matteo/Repositories/js-ipfs/node_modules/async/internal/eachOfLimit.js:66:17)
    at iterateeCallback (/Users/matteo/Repositories/js-ipfs/node_modules/async/internal/eachOfLimit.js:50:17)
    at /Users/matteo/Repositories/js-ipfs/node_modules/async/internal/onlyOnce.js:12:16
    at _sendSafeBlocks (/Users/matteo/Repositories/js-ipfs/node_modules/ipfs-bitswap/src/decision-engine/index.js:71:11)
```

**Comment by mcollina** [comment]
Some other times I'm getting:

```
/Users/matteo/Repositories/js-ipfs/node_modules/proper-lockfile/lib/lockfile.js:181
        onCompromised: (err) => { throw err; },
                                  ^

Error: ENOENT: no such file or directory, utime 'data/ipfs/849313/repo.lock'
```

**Comment by litzenberger** [comment]
OK, I'll do more test.

**Comment by litzenberger** [comment]
https://github.com/ipfs/js-ipfs/issues/1761

**Comment by litzenberger** [comment]
From my recent testing, this has been fixed by this PR https://github.com/ipfs/benchmarks/pull/78

I'm going to close this and will re-open if it appears.
