### ISSUE TITLE
Error when running locally with Dashboard

### ISSUE THREAD

**Issue by litzenberger** [ipfs/benchmarks#66]
```
rons-MBP:benchmarks ronlitzenberger$ STAGE=local LOG_PRETTY=true node runner/cli.js
INFO [1544553155694] (99751 on rons-MBP.attlocal.net): Running [OUT_FOLDER=/tmp/out  node /Users/ronlitzenberger/nearform/ipfs/benchmarks/tests/local-transfer.js] locally
INFO [1544553298798] (99751 on rons-MBP.attlocal.net): Retrieving [cat /tmp/out/localTransfer.json] locally
INFO [1544553298807] (99751 on rons-MBP.attlocal.net):
    err: {
      "type": "Error",
      "message": "Command failed: cat /tmp/out/localTransfer.json\ncat: /tmp/out/localTransfer.json: No such file or directory\n",
      "stack":
          Error: Command failed: cat /tmp/out/localTransfer.json
          cat: /tmp/out/localTransfer.json: No such file or directory

              at ChildProcess.exithandler (child_process.js:289:12)
              at ChildProcess.emit (events.js:182:13)
              at maybeClose (internal/child_process.js:962:16)
              at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
      "killed": false,
      "code": 1,
      "signal": null,
      "cmd": "cat /tmp/out/localTransfer.json"
    }
    stdout: ""
    stderr: "cat: /tmp/out/localTransfer.json: No such file or directory\n"
ERROR [1544553298808] (99751 on rons-MBP.attlocal.net): cat: /tmp/out/localTransfer.json: No such file or directory

    Error: cat: /tmp/out/localTransfer.json: No such file or directory

        at exec (/Users/ronlitzenberger/nearform/ipfs/benchmarks/runner/local.js:31:20)
        at ChildProcess.exithandler (child_process.js:296:5)
        at ChildProcess.emit (events.js:182:13)
        at maybeClose (internal/child_process.js:962:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5
```

**Comment by Elexy** [comment]
STAGE=local is the culprit here, let me have a look.

**Comment by litzenberger** [comment]
I'll update the README on my branch and remove `STAGE=local`
